### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by oscar-lima** [DFKI-NI/mobipick_labs#1]
In step ```./install-deps.sh```

```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'
```

Complete log error
```
--- Logging error ---
Traceback (most recent call last):
  File "/home/oscar/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "/home/oscar/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py", line 1752, in print
    extend(render(renderable, render_options))
  File "/home/oscar/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py", line 1390, in render
    for render_output in iter_render:
  File "/home/oscar/.local/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 134, in __rich_console__
    for line in lines:
  File "/home/oscar/.local/lib/python3.8/site-packages/pip/_vendor/rich/segment.py", line 245, in split_lines
    for segment in segments:
  File "/home/oscar/.local/lib/python3.8/site-packages/pip/_vendor/rich/console.py", line 1368, in render
    renderable = rich_cast(renderable)
  File "/home/oscar/.local/lib/python3.8/site-packages/pip/_vendor/rich/protocol.py", line 36, in rich_cast
    renderable = cast_method()
  File "/home/oscar/.local/lib/python3.8/site-packages/pip/_internal/self_outdated_check.py", line 130, in __rich__
    pip_cmd = get_best_invocation_for_this_pip()
  File "/home/oscar/.local/lib/python3.8/site-packages/pip/_internal/utils/entrypoints.py", line 58, in get_best_invocation_for_this_pip
    if found_executable and os.path.samefile(
  File "/usr/lib/python3.8/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/pip3.8'
```

**Comment by oscar-lima** [comment]
Apparently doing ```pip3 install --upgrade pip``` helped

**Comment by mintar** [comment]
Just never run that command using "sudo"! :)

**Comment by mintar** [comment]
BTW, I didn't get that problem, and I'm using the system version of pip (`/usr/bin/pip`). In general I try to install as few Python packages as possible to `~/.local`, because it leads to problems like this.
